version: '3.8'

services:
  INTRA - MPO-db:
    image: postgres:16-alpine
    container_name: INTRA - MPO-postgres
    restart: unless-stopped
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: INTRA - MPO
      POSTGRES_USER: INTRA - MPO_user
      POSTGRES_PASSWORD: INTRA - MPO_2024_iglesia
    volumes:
      - INTRA - MPO_pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U INTRA - MPO_user -d INTRA - MPO"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  INTRA - MPO_pgdata:
    driver: local
