version: '3.8'

services:
  intrampo-db:
    image: mongo:7
    container_name: intrampo-mongo
    command: ["--replSet", "rs0", "--bind_ip_all", "--port", "27018"]
    restart: unless-stopped
    ports:
      - "27018:27018"
    volumes:
      # Guardaremos los datos físicamente en una carpeta "mongo-data" 
      # dentro de este mismo proyecto (en tu disco D:)
      - ./mongo-data:/data/db
    healthcheck:
      test: test $$(echo "rs.initiate({_id:'rs0',members:[{_id:0,host:\"localhost:27018\"}]}).ok || rs.status().ok" | mongosh --port 27018 --quiet) -eq 1
      interval: 10s
      start_period: 30s
